version: '2.27.0'

services:
  api-solid-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESSQL_USERNAME=docker
      - POSTGRESSQL_USERNAME=docker
      - POSTGRESSQL_DATABASE=apisolid