name: Run e2e Tests

on: [pull_request]

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    services:
  api-solid-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    env:
      POSTGRESSQL_USERNAME: docker
      POSTGRESSQL_USERNAME: docker
      POSTGRESSQL_DATABASE: apisolid

    steps:
      - users: action/checkout@v3

      - uses: actions/setup-node@v3
        with: 
         node-version: 18
         cache: 'npm'

      - run: npm ci

      - run: npm run test